apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: {{ include "spring-sample.fullname" . }}
spec:
  splits:
    - serviceSubset: jerry
      weight: 100
    - serviceSubset: tom
      weight: 0