apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver         
metadata:
  name: {{ include "spring-sample.fullname" . }}
spec:
  subsets:
    tom:
      filter: 'Service.Meta.version == tom'
    jerry:
      filter: 'Service.Meta.version == jerry'